version: '3'
services:
  apache:
    container_name: apache
    build: apache
    volumes:
      - ./src/php:/var/www/html-dynamic
    ports:
      - 8081:8081
  nginx:
    container_name: nginx
    build: nginx
    volumes:
      - ./src/static:/usr/share/nginx/html-static
    ports:
      - 8082:8082
  db:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    volumes: 
      - ./init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    ports:
      - 8080:8080
