version: "3.8"

services:
  drawer:
    build: ./
    volumes:
      - "./drawer:/var/www/html"
    ports:
      - "8080:80"
  
  sort:
    build: ./
    volumes:
      - "./sort:/var/www/html"
    ports:
      - "8081:80"

  shell:
    build: ./
    volumes:
      - "./shell:/var/www/html"
    ports:
      - "8082:80"
